services:
  frontend:
    build:
      context: ./miniaturl
    ports:
      - 5173:5173
    volumes:
      - ./miniaturl/src:/app/src
    depends_on:
      - api

  api:
    build:
      context: ./miniaturl-api
    ports:
      - 5000:5000
    volumes:
      - ./miniaturl-api/src:/app/src
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: